# -*- coding: utf-8 -*-
"""Exam_Final_Diabetes_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xYOa5PWaqA_5UB-R_EwjbUEwIZdwDZr-
"""

# =============================================================================
# DIABETES RISK PREDICTOR
# Neural Network built with TensorFlow, NumPy, and OOP
# Team: Miguel, Joshua, Jesse, Ray
# =============================================================================
# FILE: diabetes_predictor.py
# This file contains the DiabetesPredictor class — the core of the project.
# It handles everything: loading data, preprocessing, building the model,
# training, evaluation, and prediction.
# =============================================================================

# --- IMPORTS -----------------------------------------------------------------
# These are all the external libraries the program needs.

import numpy as np                              # For data manipulation and math
import pandas as pd                             # For loading the CSV file
import tensorflow as tf                         # For building the neural network
from tensorflow import keras                    # Keras is TensorFlow's user-friendly API
from tensorflow.keras import layers            # Layers are the building blocks of the network
from sklearn.model_selection import train_test_split  # Splits data into train/test sets
from sklearn.preprocessing import StandardScaler      # Normalizes our features
import matplotlib.pyplot as plt                # For plotting training graphs (extra feature)
import os                                       # For file path handling

# --- REPRODUCIBILITY ---------------------------------------------------------
# Setting a random seed makes results consistent every time the program runs.
# Without this, the network initializes weights randomly and results vary.
np.random.seed(42)
tf.random.set_seed(42)


# =============================================================================
# THE MAIN CLASS
# =============================================================================
# OOP REQUIREMENT: This class satisfies the OOP component of the exam.
# It has:
#   - Clear attributes defined in __init__
#   - More than 3 methods with distinct functionalities
#   - Proper encapsulation (data is stored inside the object, not as globals)
#   - Coherent integration with the neural network workflow

class DiabetesPredictor:
    """
    A neural network-based classifier that predicts diabetes risk
    using the Pima Indians Diabetes Dataset.

    Attributes
    ----------
    dataset_path : str
        Path to the CSV file containing the dataset.
    model : keras.Sequential or None
        The TensorFlow neural network model. None until build_model() is called.
    scaler : StandardScaler
        The normalization object. Fitted on training data, applied to all data.
    history : keras.callbacks.History or None
        Records accuracy and loss at each training epoch. None until train() is called.
    X_train, X_test : numpy.ndarray
        Feature arrays for training and testing. Shape: (samples, 8).
    y_train, y_test : numpy.ndarray
        Label arrays for training and testing. Shape: (samples,). Values: 0 or 1.
    input_shape : int
        Number of input features (always 8 for this dataset).
    """

    def __init__(self, dataset_path: str):
        """
        Initialize the DiabetesPredictor.

        This method runs automatically when you create a DiabetesPredictor object.
        It sets up all the attributes but does NOT load data or build the model yet —
        those steps are separate so they can be called in a clear, readable order.

        Parameters
        ----------
        dataset_path : str
            The file path to the diabetes CSV file.
            Example: 'data/diabetes.csv'
        """
        # Store the path to the CSV file
        self.dataset_path = dataset_path

        # The neural network model — starts as None, gets created in build_model()
        self.model = None

        # The scaler normalizes our data so all features are on the same scale
        # This is created here but fitted (calculated) in load_and_preprocess()
        self.scaler = StandardScaler()

        # Training history — stores accuracy and loss per epoch for graphing
        self.history = None

        # These will hold our processed data arrays after load_and_preprocess()
        self.X_train = None   # Training features (8 columns, many rows)
        self.X_test  = None   # Testing features  (8 columns, fewer rows)
        self.y_train = None   # Training labels   (0 or 1 per patient)
        self.y_test  = None   # Testing labels    (0 or 1 per patient)

        # The number of input features (columns) — 8 for the Pima dataset
        # This gets set correctly during load_and_preprocess()
        self.input_shape = 8

        print("DiabetesPredictor initialized.")
        print(f"Dataset path: {self.dataset_path}")


    # =========================================================================
    # METHOD 1: load_and_preprocess()
    # Owner: Jesse (CSV loading) + Ray (NumPy normalization)
    # =========================================================================
    def load_and_preprocess(self, test_size: float = 0.2):
        """
        Load the CSV file and prepare the data for the neural network.

        This method performs 5 steps:
          1. Load the CSV into a pandas DataFrame
          2. Separate features (X) from the target label (y)
          3. Split into training and testing sets
          4. Normalize the features using StandardScaler
          5. Convert everything to NumPy float32 arrays (required by TensorFlow)

        Parameters
        ----------
        test_size : float, optional
            Fraction of data reserved for testing. Default is 0.2 (20%).
            The remaining 80% is used for training.

        Returns
        -------
        None
            Results are stored in self.X_train, self.X_test, self.y_train, self.y_test
        """

        # ----- STEP 1: Load the CSV file -------------------------------------
        # Jesse's responsibility: reading the file, checking it loaded correctly

        print("\n--- Step 1: Loading dataset ---")

        # Verify the file exists before trying to load it
        if not os.path.exists(self.dataset_path):
            raise FileNotFoundError(
                f"Dataset not found at: {self.dataset_path}\n"
                f"Download it from: https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database"
            )

        # pd.read_csv reads the CSV and turns it into a DataFrame (like a table)
        df = pd.read_csv(self.dataset_path)

        # Print basic info so we can verify the file loaded correctly
        print(f"  Loaded {len(df)} rows and {len(df.columns)} columns.")
        print(f"  Columns: {list(df.columns)}")

        # Check for missing values — the Pima dataset uses 0 for missing medical data
        # We replace zeros in medical columns with the column mean to avoid bias
        medical_columns = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
        for col in medical_columns:
            zero_count = (df[col] == 0).sum()
            if zero_count > 0:
                col_mean = df[col].replace(0, np.nan).mean()
                df[col] = df[col].replace(0, col_mean)
                print(f"  Replaced {zero_count} zero(s) in '{col}' with mean ({col_mean:.2f})")

        # ----- STEP 2: Separate features (X) from target label (y) ----------
        # Jesse's responsibility: correctly identifying which column is the target

        print("\n--- Step 2: Separating features and labels ---")

        # X contains the 8 input features — everything EXCEPT 'Outcome'
        # These are what the network will learn from
        X = df.drop(columns=['Outcome']).values   # .values converts DataFrame to NumPy array

        # y contains the target label: 0 = no diabetes, 1 = diabetes
        y = df['Outcome'].values

        # Update input_shape to match the actual number of features
        self.input_shape = X.shape[1]

        print(f"  Features shape: {X.shape}  → {X.shape[0]} patients, {X.shape[1]} features each")
        print(f"  Labels shape:   {y.shape}  → {y.shape[0]} labels (0 or 1)")
        print(f"  Positive cases (diabetes=1): {y.sum()} ({y.mean()*100:.1f}%)")
        print(f"  Negative cases (diabetes=0): {(1-y).sum()} ({(1-y.mean())*100:.1f}%)")

        # ----- STEP 3: Train/Test Split --------------------------------------
        # Jesse's responsibility: splitting the data correctly

        print("\n--- Step 3: Splitting into train and test sets ---")

        # train_test_split randomly divides the data
        # test_size=0.2 means 20% goes to testing, 80% to training
        # random_state=42 makes the split the same every time (reproducibility)
        # stratify=y ensures both splits have similar proportions of 0s and 1s
        X_train, X_test, y_train, y_test = train_test_split(
            X, y,
            test_size=test_size,
            random_state=42,
            stratify=y        # Keeps class balance in both splits
        )

        print(f"  Training samples:  {len(X_train)} ({100 - test_size*100:.0f}%)")
        print(f"  Testing samples:   {len(X_test)} ({test_size*100:.0f}%)")

        # ----- STEP 4: Normalize the features --------------------------------
        # Ray's responsibility: NumPy normalization using StandardScaler
        #
        # WHY NORMALIZE?
        # The 8 features have very different ranges:
        #   - Glucose: 0 to 200
        #   - DiabetesPedigreeFunction: 0.08 to 2.42
        # Without normalization, Glucose would dominate the learning process
        # simply because its numbers are larger, not because it's more important.
        # StandardScaler transforms each feature to have mean=0 and std=1.

        print("\n--- Step 4: Normalizing features ---")

        # IMPORTANT: fit_transform on TRAINING data only
        # We learn the mean and std from training data, then apply the same
        # transformation to test data. This prevents "data leakage" —
        # the model should never see test data statistics during training.
        X_train_scaled = self.scaler.fit_transform(X_train)

        # transform (not fit_transform) on test data — uses training statistics
        X_test_scaled = self.scaler.transform(X_test)

        print(f"  Before normalization — Glucose mean: {X_train[:, 1].mean():.2f}, std: {X_train[:, 1].std():.2f}")
        print(f"  After normalization  — Glucose mean: {X_train_scaled[:, 1].mean():.2f}, std: {X_train_scaled[:, 1].std():.2f}")

        # ----- STEP 5: Convert to float32 NumPy arrays ----------------------
        # Ray's responsibility: correct data type conversion for TensorFlow
        #
        # TensorFlow works with 32-bit floating point numbers (float32).
        # Python/NumPy defaults to float64. We must convert explicitly.
        # This also ensures the arrays are stored contiguously in memory
        # for efficient TensorFlow processing.

        print("\n--- Step 5: Converting to float32 ---")

        self.X_train = np.array(X_train_scaled, dtype=np.float32)
        self.X_test  = np.array(X_test_scaled,  dtype=np.float32)
        self.y_train = np.array(y_train,         dtype=np.float32)
        self.y_test  = np.array(y_test,          dtype=np.float32)

        print(f"  X_train: shape={self.X_train.shape}, dtype={self.X_train.dtype}")
        print(f"  X_test:  shape={self.X_test.shape},  dtype={self.X_test.dtype}")
        print(f"  y_train: shape={self.y_train.shape}, dtype={self.y_train.dtype}")
        print(f"  y_test:  shape={self.y_test.shape},  dtype={self.y_test.dtype}")

        # ----- EXTRA NUMPY OPERATIONS ---------------------------------------
        # Explicitly using NumPy to verify the normalization across all columns
        # axis=0 means we calculate the mean/std for each column separately
        feature_means = np.mean(self.X_train, axis=0)
        feature_stds = np.std(self.X_train, axis=0)

        print("\n  [NumPy Check] Verifying normalization (Means ~ 0, Stds ~ 1):")
        print(f"  Means (all 8 features): {np.round(feature_means, 2)}")
        print(f"  Stds  (all 8 features): {np.round(feature_stds, 2)}")
        print("\nData loading and preprocessing complete.")


    # =========================================================================
    # METHOD 2: build_model()
    # Owner: Miguel
    # =========================================================================
    def build_model(self):
        """
        Define and compile the neural network architecture.

        This method:
          1. Creates a Sequential model (layers stacked one after another)
          2. Adds Dense (fully connected) layers with ReLU activation
          3. Adds Dropout layers to prevent overfitting
          4. Adds an output layer with Sigmoid activation for binary classification
          5. Compiles the model with an optimizer, loss function, and metrics

        The architecture chosen:
          Input (8)  →  Dense(32, ReLU)  →  Dropout(0.3)
                     →  Dense(16, ReLU)  →  Dropout(0.3)
                     →  Dense(1, Sigmoid)  →  Output (0 to 1)

        Returns
        -------
        None
            The compiled model is stored in self.model
        """

        print("\n--- Building the neural network ---")

        # Verify data is loaded before building the model
        if self.X_train is None:
            raise RuntimeError("Call load_and_preprocess() before build_model().")

        # ----- CREATE THE MODEL ----------------------------------------------
        # Sequential means layers are stacked in a straight line.
        # Data flows from top to bottom through each layer.
        self.model = keras.Sequential(name="DiabetesPredictor")

        # ----- LAYER 1: Input + First Hidden Layer ---------------------------
        # Dense(32) means 32 neurons.
        # input_shape tells Keras the shape of one input sample (8 features).
        # activation='relu' applies the ReLU function to each neuron's output.
        #
        # WHAT IS ReLU?
        # ReLU stands for Rectified Linear Unit.
        # It outputs 0 if the input is negative, or the input itself if positive.
        # Formula: f(x) = max(0, x)
        # It's the most popular activation for hidden layers because:
        #   - It's simple and fast to compute
        #   - It avoids the "vanishing gradient" problem that Sigmoid has
        self.model.add(layers.Dense(
            units=32,
            activation='relu',
            input_shape=(self.input_shape,),  # (8,) — one value per feature
            name='hidden_layer_1'
        ))

        # ----- DROPOUT AFTER LAYER 1 -----------------------------------------
        # Dropout randomly "turns off" a fraction of neurons during training.
        # rate=0.3 means 30% of neurons are ignored each training step.
        #
        # WHY DROPOUT?
        # It prevents overfitting — when the network memorizes training data
        # instead of learning general patterns. By randomly disabling neurons,
        # the network can't rely too heavily on any one neuron and is forced
        # to distribute knowledge across many neurons.
        # Dropout is ONLY active during training — it's disabled during evaluation.
        self.model.add(layers.Dropout(rate=0.3, name='dropout_1'))

        # ----- LAYER 2: Second Hidden Layer ----------------------------------
        # 16 neurons — fewer than the first layer.
        # This funnel shape (32 → 16 → 1) is common practice:
        # early layers learn broad patterns, later layers refine them.
        self.model.add(layers.Dense(
            units=16,
            activation='relu',
            name='hidden_layer_2'
        ))

        # ----- DROPOUT AFTER LAYER 2 -----------------------------------------
        self.model.add(layers.Dropout(rate=0.3, name='dropout_2'))

        # ----- OUTPUT LAYER --------------------------------------------------
        # units=1 because we want a single output: the probability of diabetes.
        # activation='sigmoid' squashes any number into the range [0, 1].
        #
        # WHAT IS SIGMOID?
        # Formula: f(x) = 1 / (1 + e^(-x))
        # It maps any real number to a value between 0 and 1.
        # We interpret this as a probability:
        #   - Output close to 0 → likely no diabetes
        #   - Output close to 1 → likely has diabetes
        # We use a threshold of 0.5: >= 0.5 means "at risk", < 0.5 means "not at risk"
        #
        # WHY SIGMOID IN OUTPUT BUT NOT HIDDEN LAYERS?
        # Sigmoid causes the vanishing gradient problem in hidden layers.
        # But for the final output of a binary classifier, we specifically want
        # a probability between 0 and 1 — sigmoid is perfect for that.
        self.model.add(layers.Dense(
            units=1,
            activation='sigmoid',
            name='output_layer'
        ))

        # ----- COMPILE THE MODEL --------------------------------------------
        # Compiling configures how the model will learn.
        # Three things must be specified:

        self.model.compile(
            # OPTIMIZER: adam (Adaptive Moment Estimation)
            # Adam adjusts the learning rate automatically during training.
            # It's the most widely used optimizer — a safe default for most problems.
            # learning_rate=0.001 is Adam's default and works well here.
            optimizer=keras.optimizers.Adam(learning_rate=0.001),

            # LOSS FUNCTION: binary_crossentropy
            # This measures how wrong the predictions are.
            # "Binary" because we have exactly 2 classes (diabetes / no diabetes).
            # Cross-entropy penalizes confident wrong answers more than uncertain ones.
            # The training process tries to MINIMIZE this number.
            loss='binary_crossentropy',

            # METRICS: what we want to track and display during training
            # 'accuracy' = the percentage of predictions that were correct
            metrics=['accuracy']
        )

        # Print a summary of the model architecture
        print("\nModel architecture:")
        self.model.summary()

        print("\nModel compiled successfully.")
        print("  Optimizer:     Adam (learning_rate=0.001)")
        print("  Loss function: binary_crossentropy")
        print("  Metric:        accuracy")


    # =========================================================================
    # METHOD 3: train()
    # Owner: Miguel
    # =========================================================================
    def train(self, epochs: int = 50, batch_size: int = 32):
        """
        Trains the neural network.

        Calls model.fit() to train the network and stores the training
        history (accuracy and loss per epoch) in self.history.
        """
        print("\n--- Step 6: Training the neural network ---")

        if self.model is None:
            raise RuntimeError("Call build_model() before train().")

        # ----- TRAIN THE MODEL ----------------------------------------------
        # fit() is the function that actually teaches the network.
        #
        # WHAT IS AN EPOCH?
        # An epoch is one complete pass through the entire training dataset.
        # If epochs=50, the model looks at all patients 50 times to learn.
        #
        # WHAT IS BATCH_SIZE?
        # Instead of updating the model's weights after every single patient (too erratic)
        # or after all patients at once (too slow), we update it in small batches.
        # batch_size=32 means the model learns from 32 patients, updates, and repeats.
        #
        # WHY VALIDATION_SPLIT?
        # validation_split=0.2 holds back 20% of the TRAINING data. At the end of
        # each epoch, the model tests itself on this 20%. This ensures the model
        # is actually learning general patterns, not just memorizing the training data.
        self.history = self.model.fit(
            self.X_train,
            self.y_train,
            epochs=epochs,
            batch_size=batch_size,
            validation_split=0.2,
            verbose=1  # Shows a progress bar in the terminal
        )

        print("\nTraining complete.")

    # =========================================================================
    # METHOD 4: evaluate()
    # Owner: Miguel
    # =========================================================================
    def evaluate(self):
        """
        Evaluates the model on the test set.

        Calls model.evaluate() on the test set — data the model has never seen.
        Prints final test accuracy and loss.
        """
        print("\n--- Step 7: Evaluating the model ---")

        if self.model is None or self.history is None:
            raise RuntimeError("Model must be built and trained before evaluate().")

        # ----- EVALUATE ON UNSEEN DATA --------------------------------------
        # WHY EVALUATE WHEN WE ALREADY HAVE VALIDATION DATA?
        # During training, we (and the model) look at the validation scores to
        # tweak settings. Because of this, the validation data is slightly "tainted".
        # The test set (X_test, y_test) has been completely hidden from the model
        # since Step 3. This gives us the truest measure of real-world performance.
        loss, accuracy = self.model.evaluate(self.X_test, self.y_test, verbose=0)

        print(f"  Final Test Loss:     {loss:.4f}")
        print(f"  Final Test Accuracy: {accuracy * 100:.2f}%")

        return loss, accuracy

    # =========================================================================
    # METHOD 5: predict()
    # Owner: Miguel
    # =========================================================================
    def predict(self, patient_data: np.ndarray):
        """
        Predicts diabetes risk for a single patient.

        Accepts a NumPy array of shape (1, 8) representing one patient's measurements.
        Runs model.predict() and returns both the probability and interpretation.
        """
        if self.model is None:
            raise RuntimeError("Model must be trained before predicting.")

        # Ensure the input array is exactly shape (1, 8) — 1 patient, 8 features
        if patient_data.shape != (1, 8):
            patient_data = patient_data.reshape(1, 8)

        # ----- SCALE THE NEW DATA -------------------------------------------
        # WHY USE transform() INSTEAD OF fit_transform()?
        # We MUST normalize the new patient's data using the exact same scale
        # the model learned during training. If we fit a new scaler, the numbers
        # won't mean the same thing to the neural network.
        patient_data_scaled = self.scaler.transform(patient_data)

        # predict() outputs a 2D array, we extract the single float value
        probability = self.model.predict(patient_data_scaled, verbose=0)[0][0]

        # Apply our threshold to determine the human-readable interpretation.
        # Since we used a Sigmoid activation in the final layer, the output is
        # a probability between 0 and 1. >= 0.5 means "at risk".
        interpretation = "At risk" if probability >= 0.5 else "Low risk"

        print("\n--- Step 8: Patient Prediction ---")
        print(f"  Prediction Probability: {probability:.4f} ({(probability * 100):.1f}%)")
        print(f"  Interpretation:         {interpretation}")

        return probability, interpretation

    # =========================================================================
    # METHOD 6: plot_training_history()
    # Owner: Miguel
    # =========================================================================
    def plot_training_history(self):
        """
        Plots the training and validation accuracy and loss using Matplotlib.
        """
        print("\n--- Step 9: Plotting training history ---")

        if self.history is None:
            raise RuntimeError("Model must be trained before plotting history.")

        # ----- VISUALIZE LEARNING -------------------------------------------
        # WHY PLOT THIS?
        # Plotting accuracy and loss helps us spot 'overfitting'.
        # If the training accuracy (blue line) keeps going up, but the validation
        # accuracy (orange line) stalls or goes down, the model is just memorizing
        # the training data and failing to generalize.

        # Create a figure with 1 row and 2 columns
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

        # Graph 1: Accuracy
        ax1.plot(self.history.history['accuracy'], label='Train Accuracy', color='blue')
        ax1.plot(self.history.history['val_accuracy'], label='Validation Accuracy', color='orange')
        ax1.set_title('Model Accuracy over Epochs')
        ax1.set_xlabel('Epoch')
        ax1.set_ylabel('Accuracy')
        ax1.legend()
        ax1.grid(True, linestyle='--', alpha=0.7)

        # Graph 2: Loss (Binary Cross-entropy)
        ax2.plot(self.history.history['loss'], label='Train Loss', color='blue')
        ax2.plot(self.history.history['val_loss'], label='Validation Loss', color='orange')
        ax2.set_title('Model Loss over Epochs')
        ax2.set_xlabel('Epoch')
        ax2.set_ylabel('Loss (Binary Cross-entropy)')
        ax2.legend()
        ax2.grid(True, linestyle='--', alpha=0.7)

        # Adjust layout and display
        plt.tight_layout()
        plt.show()


# =============================================================================
# PIPELINE EXECUTION (Entry Point)
# Owner: Joshua
# =============================================================================
# This block ties together everything built in Phase 1 and Phase 2
# into a single, cohesive pipeline.
# =============================================================================
print("=" * 60)
print("Running DiabetesPredictor — Full Pipeline (Phases 1 & 2)")
print("=" * 60)

# 1. Instantiate the class
predictor = DiabetesPredictor(dataset_path='diabetes.csv')

# 2. Phase 1: Pipeline & Architecture
predictor.load_and_preprocess(test_size=0.2)
predictor.build_model()

# 3. Phase 2: Training & Evaluation
# 100 epochs is a good baseline for this dataset
predictor.train(epochs=100, batch_size=32)
predictor.evaluate()

# 4. Example Prediction (Dynamic test with a real patient from the database)
# Read the original CSV file directly using pandas
df_real = pd.read_csv('diabetes.csv')

# Take one random patient from the database (.sample(1) picks a random row)
random_patient = df_real.sample(1, random_state=None)

# Extract only the 8 medical features (drop the 'Outcome' column)
# .values converts it to the NumPy array of shape (1, 8) that predict() expects
patient_features = random_patient.drop(columns=['Outcome']).values

# Save the real outcome to compare it with the model's prediction
real_outcome = random_patient['Outcome'].values[0]
real_status = "At risk" if real_outcome == 1 else "Low risk"

print("\n" + "-" * 40)
print(" TESTING WITH A RANDOM PATIENT FROM DB")
print("-" * 40)

# AQUÍ IMPRIMIMOS LA TUPLA SELECCIONADA
print("  Selected Patient Data:")
# Usamos to_string(index=False) para que se imprima como una tabla limpia sin el ID de fila
print(random_patient.drop(columns=['Outcome']).to_string(index=False))

print(f"\n  Real diagnosis in Database: {real_status} (Outcome={real_outcome})")

# Pass the patient's features to the predict() method
predictor.predict(patient_features)

# 5. Visualization
predictor.plot_training_history()

print("\n" + "=" * 60)
print("Pipeline Execution Complete.")
print("=" * 60)